
import './globals.css'
import 'font-awesome/css/font-awesome.min.css';
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Icon from '@/public/medias/ABSICON.png'
import {Provider} from 'react-redux'
import {Store} from './context/store'
import Wrapper from './context/features/wrapper'
import Head from 'next/head'


const inter = Inter({subsets: ['latin']})

Icon.height *= 2
export const metadata: Metadata = {
  title: 'ABS',
  icons: Icon.src,
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>

      </Head>
      <body className={inter.className}>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  )
}
